var annotated_dup =
[
    [ "OceanSim", "namespace_ocean_sim.html", "namespace_ocean_sim" ],
    [ "ActiveStateToggler", "class_active_state_toggler.html", null ],
    [ "AnimationHashTable", "class_animation_hash_table.html", "class_animation_hash_table" ],
    [ "ApplicationManager", "class_application_manager.html", "class_application_manager" ],
    [ "BounceNBreak", "class_bounce_n_break.html", null ],
    [ "ChangeColor", "class_change_color.html", null ],
    [ "Checkpoint", "class_checkpoint.html", "class_checkpoint" ],
    [ "DragMe", "class_drag_me.html", null ],
    [ "DragPanel", "class_drag_panel.html", null ],
    [ "DropMe", "class_drop_me.html", null ],
    [ "ExactWaterHeight", "class_exact_water_height.html", null ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "GetWinner", "class_get_winner.html", "class_get_winner" ],
    [ "HeightInWater", "class_height_in_water.html", null ],
    [ "LoadSceneOnClick", "class_load_scene_on_click.html", null ],
    [ "MenuButton", "class_menu_button.html", "class_menu_button" ],
    [ "MeshModify", "class_mesh_modify.html", "class_mesh_modify" ],
    [ "MoveTo", "class_move_to.html", "class_move_to" ],
    [ "PanelManager", "class_panel_manager.html", null ],
    [ "PathingWaypoint", "class_pathing_waypoint.html", "class_pathing_waypoint" ],
    [ "PlayerManager", "class_player_manager.html", "class_player_manager" ],
    [ "PlayerManagerLoader", "class_player_manager_loader.html", null ],
    [ "PlayerMovement", "class_player_movement.html", "class_player_movement" ],
    [ "PlayerSplash", "class_player_splash.html", "class_player_splash" ],
    [ "PowerUp", "class_power_up.html", "class_power_up" ],
    [ "ResizePanel", "class_resize_panel.html", null ],
    [ "Rotator", "class_rotator.html", null ],
    [ "ScrollDetailTexture", "class_scroll_detail_texture.html", null ],
    [ "ShowSliderValue", "class_show_slider_value.html", null ],
    [ "SimpleBoyancy", "class_simple_boyancy.html", null ],
    [ "slowDown", "classslow_down.html", "classslow_down" ],
    [ "TiltWindow", "class_tilt_window.html", null ],
    [ "TriangleType", "struct_triangle_type.html", null ],
    [ "WaterConsole", "class_water_console.html", null ]
];